stages:
- test
- deploy

language: python

before_install:
- pip install poetry

install:
- poetry check
- poetry install

script:
- poetry run isort -rc -c --diff aioeafm tests
- poetry run black aioeafm tests --check --diff
- poetry run flake8 aioeafm tests
- poetry run mypy aioeafm
- poetry run pylint aioeafm
- poetry run coverage run -m pytest tests/
- poetry build

after_success:
- poetry run codecov

jobs:
  include:
  - os: linux
    dist: xenial
    python: 3.7

  - os: linux
    dist: xenial
    python: 3.8

  - stage: deploy
    dist: xenial
    python: 3.7
    script:
    - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
    - poetry build
    after_success: 'true'
    deploy:
    - provider: script
      skip_cleanup: true
      script: poetry publish
      on:
        repo: Jc2k/aioeafm
        tags: true
    - provider: releases
      skip_cleanup: true
      api_key:
        secure: Arazs2T9edxQ/YY9c1FVt1WSz8wHRnkBHoNzbLwwIQ3v3InKkSjBTaXx/bkMGlqIkGiI0ExW5cJl/pmESXJAFE+2fxb3LK7FKrZB/1bAbD/fKFToEhUTUf8FHgQPjzSAW9k4zoieQPtRzmda99GbZgfqPfYaC/DgZ2bOjdbuSgEYHqQbC1HtykY6HFD522WVIF4/ZrkxXDc4srQzCoBxpUpJXCzrPZlGv+/aZpH4Il/tMdza15hNeSlT9Gj2bCx0k2LmzTH/+iKWUocMtqwQKMyRdIn/NSBQkJ8XMSPp261YpkJYH0m3g5ACwSRmnnxz21E8oM7jDvx6lkU5I+CJggrIRq6JCY/mYMEkjbihsHNz3rUfDaewZzIphg8boNaYOfi+sVVRLrLyMGRx5AG1XumpKxcBZlS6UP7aqn4T8uvbUmOqfi7tY3hnqr5fP7Zhcr5COl3+FS/BKTefqHJqLyI1wQpQsE46qD4JKWAkzLMC92NdCnLA6eFQ9jeG3KG38KuezDguQJjHgNi85lQQeRxAi5jLezWvtxWLouU5CZqqutgwTyr1xjFeq7lXKGwjJ0ylj/dMJpm32OVSBNH1DHO8LEoNxmmY5q/2d7NanteAtneHnAnYnLL3dnT91P0IQaNDik/1fVEEvLxlCxoxHTAcjexsaWozlmrtA7bif0k=
      file_glob: true
      file: dist/*
      on:
        repo: Jc2k/aioeafm
        tags: true

env:
  global:
    secure: jr52rQOMOVjdc/Xz84uP+6akCZSAXJfIJitcUV6mQeRUGm4MJv6Dn/OFgzVtS6sN/Pp3gcTPUFk2V1rWQBxGEOKfwZ66sEhmIdNB6ikpBzkXXK10AAZqaVvA5mU/dXe2fwQOWXhS+TkpOf0/oa8hIN8e2+lzKZnVpADGnOK8EZj98+HznCB40NxGhi9ED9bJ4mp9PIsRVyuzOyVnKVO45/1D/O5VYRXoNTvC6ayc+egOiIlBpwhMSQCJM7zFm1QL3QY0ucVBHVqXAyMqz0AH6Z1pF/OL4Tp7G6ExtFhj+sSnPH1/luRiu6+wiLPIFw3iEPKUV7N5ZzrLzTrMt32Aty9mLYcutMxvAiZn0EGchatC7zDCD4YCkUc9oRei77LTnIziNyujGeh+46qfuIjxmqf4fzWdLg80D4deM3cZZBxy9P+KmmqCrqtTooVYLS8b71d0/FvDRyfkg9Nlr3EOhJIEXeQD+h5jIjXWAF/1qHkNS1lRbFMnXXa/lZBOqlZv9Q3YbsrFjLcl7dAjYiF5VrvkvQL0ZMVn9fhrieofWN57PBVpKPFwScbxg1q85RSVJbIEL6UCeK+Zo1BDz+euSuus9H0f0zGhTvLBNOvzIbIGoLg13EPVb/ZITgLQT3QZp0lzc+/HJ8UHxRXy1iwdKnZc3PJVO5jWUW152naGmnE=
