stages:
- test
- deploy

language: python

before_install:
- pip install poetry

install:
- poetry check
- poetry install

script:
- poetry run isort -rc -c --diff aioeafm tests
- poetry run black aioeafm tests --check --diff
- poetry run flake8 aioeafm tests
- poetry run mypy aioeafm
- poetry run pylint aioeafm
- poetry run coverage run -m pytest tests/
- poetry build

after_success:
- poetry run codecov

jobs:
  include:
  - os: linux
    dist: xenial
    python: 3.7

  - os: linux
    dist: xenial
    python: 3.8

  - stage: deploy
    dist: xenial
    python: 3.7
    script:
    - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
    - poetry build
    after_success: 'true'
    deploy:
    - provider: script
      skip_cleanup: true
      script: poetry publish
      on:
        repo: Jc2k/aioeafm
        tags: true
    - provider: releases
      skip_cleanup: true
      api_key:
        secure: LRKRlqKfZ5X1vPhH2fGhqLBX8cXShcV7HuM4/MaMJ8SRxF0Rde2ul6NsT6P2gzMHvTgodWf4J/w9WxA0eHbIDwzng9yhM05HdMhMytC6bzD+4IQ1REQjIKJEGvnGbewXPsYHWnszAYF/kHCnl/kn/2DyLXBUkHHoyiAItAt0cMxDmRee2dZyHOh1CU+RBxkPaQYFPrK63cT23QkOx7A9nT1UvWm/6KeaQ5T6ADd+VaR2z+SlD98CaSvPgxzkviCF1vepv8jA5VvJjiJ+8+YlzKsUa0dvQ1ybTCJKXtA5AZm1fq9FSkdLl3VI1oZBjIGtt1aiSRcK5eQNA4a8MmgoJAcxF8EHR3sVrlWXbGKZGTtulRSpsbD/OcaOyAeDvgq7dr1Q9Yr2gMTUfsmaeOEgiPpOHE+k8rch4KyqUUTUINg54SOD0TCHYxK5d3dJbB91mskG2gquyxJs/GrMoy28OloUgKF/G+FcA/4eaSN7lDboPEasbBi+7YcwPY7LCbQdJe2u+eL3ULzji5VCDeeuwyeWNrGE8cJPR1aDSybb7qBDbl9MUn8yMo2DVA6tjqrpYLJQ2cXjUkuYEZMlg5FR36ADNTp2MQONmgB9CBASjdrOD8NhgOj3IzjB9syYpNTVdMrJRM8m+3K7/wgXjSVs04mnYfRhjSQHlnk4aZQVI+A=
      file: dist/*
      on:
        repo: Jc2k/aioeafm
        tags: true

env:
  global:
    secure: j0X2rxxdhu1ivHjKeu35mR9t0OQIllJGbgvQpJYUvcCjH1GzOdM0HtCJwePLMyLkNk5wrIxY2badBWBYAWII7b/DMYRPA06GpYUeWMyxrd1ELDBJNuQJXGzvUEBM74REFGhCH6TveO+jm2sUD/OOPPLHVlK/J1G249xFB8BA/Xy8Ug9kNK+RrhC7MoaqBApbrT+njjyniGbFPkQJr34K/eeaAZ2HMoEJHBG1J6Qc8yhuoc03mI/uj4h5bnDs78pOpOYO3FOKlg8bt+qFEauF18yjvDlpyU+BnvB+SmE1IUUHDBk8WnvKoUEq1GZS2FniGrIg6dHl+zdYcWw8QSNSHGspvRgLJHYzAbODd7NUTCOmFpT89UJWE2tf3TyiHrFJugbOP+hsehEBaNHG132El4vdKnnWSuX8kQIixBjj4a+hrMcy6wYDDUgrE6el9T3FxuN5ruF7DwIn33OfJNuQTs9gPfM+pRNrNZfJDSPRZloIyY2X00p8NczcZEvrLG1EqYYCNl3zNpWrIC5Eo5f00gYgtGCHJnMRfvGoJO54w+a11LeG+LXfQ7ycKV105y5Mwx7X7wd1UvhhhIq8okvBpgYypopfIClcZZj6d805uVt6D+8YHyPUMEfPdiGrewXntFQnmXAmJNbYIlirqaQIbQY8BVPXcTFU0URMP1nVeRk=
